backend:
  name: git-gateway
  branch: feature/netlify-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: work
    label: Work
    folder: backend/work
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - name: layout
        label: Layout
        default: 'work-item'
        options:
          - { label: 'Work item', value: 'work-item' }
        widget: select
